# Generated by Django 3.0.4 on 2021-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
