# Generated by Django 3.0.4 on 2021-09-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210905_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
