# Generated by Django 3.0.4 on 2021-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210905_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fourth_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='third_image',
            field=models.ImageField(default=1, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
