# Generated by Django 3.0.4 on 2021-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210905_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
