# Generated by Django 3.0.4 on 2021-09-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210905_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
