# Generated by Django 3.0.4 on 2021-09-06 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210905_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_slide',
        ),
        migrations.RemoveField(
            model_name='post',
            name='second_slide',
        ),
        migrations.RemoveField(
            model_name='post',
            name='third_slide',
        ),
    ]
