# Generated by Django 3.0.4 on 2021-09-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210906_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='link_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_1_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
