# Generated by Django 3.0.4 on 2021-09-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210906_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='link_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_2_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
