# Generated by Django 3.0.4 on 2021-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210906_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link_1_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link_2_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
